esphome:
  name: amber-light
  
esp8266:
  board: esp01_1m

switch:
  - platform: gpio
    id: output_relay
    pin: 5
    name: "Amber Light Switch"
    restore_mode: ALWAYS_ON

light:
  - platform: neopixelbus
    variant: WS2812X
    pin: 13
    num_leds: 1
    type: GRB
    name: "Amber Light LED"
    default_transition_length: 0s
    
# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    id: ota_esphome

wifi:
  ssid: !secret iot_wifi_ssid
  password: !secret iot_wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Amber Light"
    password: ""

captive_portal:
