# See https://esphome.io/components/sprinkler.html
esphome:
  name: backyard-sprinklers

esp32:
  board: esp32dev
  framework:
    type: arduino

# Define the switches based on the zone pins
switch:
  - platform: gpio
    id: zone_1
    pin: GPIO32
    internal: true
    restore_mode: ALWAYS_OFF
  - platform: gpio
    id: zone_2
    pin: GPIO33
    internal: true
    restore_mode: ALWAYS_OFF
  - platform: gpio
    id: zone_3
    pin: GPIO25
    internal: true
    restore_mode: ALWAYS_OFF
  - platform: gpio
    id: zone_4
    pin: GPIO26
    internal: true
    restore_mode: ALWAYS_OFF

sprinkler:
  - id: backyard_controller
    main_switch: "Backyard Sprinklers"
    auto_advance_switch: "Backyard Sprinklers Auto Advance"
    reverse_switch: "Backyard Sprinklers Reverse"
    standby_switch: "Backyard Sprinklers Standby"
    queue_enable_switch: "Enable Backyard Sprinklers Queue"
    valves:
      - valve_switch: "Main Lawn"
        enable_switch: "Enable Main Lawn"
        run_duration_number: 
          name: "Main Lawn Run Duration"
          initial_value: 20
          unit_of_measurement: min
        valve_switch_id: zone_1
      - valve_switch: "Side Lawn"
        enable_switch: "Enable Side Lawn"
        run_duration_number: 
          name: "Side Lawn Run Duration"
          initial_value: 20
          unit_of_measurement: min
        valve_switch_id: zone_3
      - valve_switch: "Vegetable Patch"
        enable_switch: "Enable Vegetable Patch"
        run_duration_number:
          name: "Vegetable Run Duration"
          initial_value: 10
          unit_of_measurement: min
        valve_switch_id: zone_2
      - valve_switch: "Side Garden Bed"
        enable_switch: "Enable Side Garden Bed"
        run_duration_number: 
          name: "Side Garden Bed Run Duration"
          initial_value: 10
          unit_of_measurement: min
        valve_switch_id: zone_4

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""
  actions:
    - action: clear_queued_valves
      then:
        - sprinkler.clear_queued_valves:
            id: backyard_controller 
    - action: queue_valve
      variables:
        valve_number: int
        run_duration: int
      then:
        - sprinkler.queue_valve:
            id: backyard_controller
            valve_number: !lambda 'return valve_number;'
            run_duration: !lambda 'return run_duration;'
    - action: start_from_queue
      then:
        - sprinkler.start_from_queue:
            id: backyard_controller
    - action: start_full_cycle
      then:
        - sprinkler.start_full_cycle: backyard_controller
    - action: shutdown
      then:
        - sprinkler.shutdown: backyard_controller
    - action: pause
      then:
        - sprinkler.pause: backyard_controller
    - action: resume
      then:
        - sprinkler.resume: backyard_controller

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true



ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret iot_wifi_ssid
  password: !secret iot_wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Backyard-Sprinkler"
    password: ""

captive_portal:
