esphome:
  name: hugos-lamp
  platform: ESP8266
  board: nodemcu

light:
  - platform: fastled_clockless
    chipset: WS2811
    pin: 5
    num_leds: 6
    rgb_order: GRB
    name: "Hugo's Lamp"
    default_transition_length: 0s
    effects:
      - random:
      - strobe: 
      - flicker:
      - addressable_rainbow:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret iot_wifi_ssid
  password: !secret iot_wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Hugo's Lamp"
    password: ""

captive_portal:
