esphome:
  name: kegerator
  
esp32:
  board: esp32dev

#i2c:
  #sda: GPI35
  #scl: GPI32

#display:
  #- platform: ssd1306_i2c
    #model: "SSD1306 128x32"
    #lambda: |-
      #it.printf(0, 0, id(my_font), "Temperature: %.1f°C", id(temperature).state
one_wire:
  - platform: gpio
    pin: GPIO25

sensor:
  - platform: dallas_temp
    id: temperature
    name: "Temperature"
    update_interval: 1s
    unit_of_measurement: "°C"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 1
    filters:
      - exponential_moving_average:
          alpha: 0.8
          send_every: 30

button:
  - platform: template
    name: "Kegerator PID Climate Autotune"
    on_press:
      - climate.pid.autotune: kegerator_pid

output:
  platform: slow_pwm
  pin: GPIO16
  period: 1200s

climate:
  - platform: pid
    id: kegerator_pid
    name: "Kegerator"
    sensor: temperature
    default_target_temperature: 7°C
    cool_output: compressor
    visual:
      min_temperature: -7
      max_temperature: 32
      temperature_step: 0.1
    control_parameters:
      kp: 0
      ki: 0
      kd: 0

logger:

api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret iot_wifi_ssid
  password: !secret iot_wifi_password

  ap:
    ssid: "Kegerator"
    password: ""

captive_portal:
