esphome:
  name: side-garden-sprinkler
  platform: ESP32
  board: esp32dev

switch:
  - platform: gpio
    id: solenoid
    pin: 18
    restore_mode: ALWAYS_OFF
    internal: true

sprinkler:
  - id: side_garden_controller
    standby_switch: "Side Garden Sprinklers Standby"
    valves:
      - valve_switch: "Side Garden"
        run_duration_number: 
          name: "Side Garden Run Duration"
          initial_value: 10
          unit_of_measurement: min
        valve_switch_id: solenoid


# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret iot_wifi_ssid
  password: !secret iot_wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Side-Garden-Sprinkler"
    password: ""

captive_portal:
