esphome:
  name: smart-lamp-a7ee

esp32:
  board: esp32-s2-saola-1

wled:

light:
  - platform: neopixelbus
    variant: WS2811
    pin: GPIO13
    num_leds: 6
    type: GRB
    name: "Smart Lamp A7EE"
    default_transition_length: 0s
    effects:
      - pulse:
      - random:
      - strobe: 
      - flicker:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
      - addressable_flicker:
      - wled:

binary_sensor:
  - platform: gpio
    pin: GPIO18
    name: "Smart Lamp A7EE Button"
    filters:
      delayed_on: 10ms

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret iot_wifi_ssid
  password: !secret iot_wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "smart-lamp-a7ee"
    password: ""

captive_portal:
