esphome:
  name: tree-lights
  on_boot:
    - light.turn_on:
        id: leds
        red: 0
        green: 100%
        blue: 100%
        effect: "Scan"

esp32:
  board: esp32-s2-saola-1
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    version: 5.5.1
    sdkconfig_options:
      CONFIG_RMT_RECV_FUNC_IN_IRAM: "y"
      CONFIG_RMT_ISR_IRAM_SAFE: "y"

light:
  - platform: esp32_rmt_led_strip
    id: leds
    rgb_order: BGR
    chipset: WS2812
    pin: GPIO15
    num_leds: 39
    # rmt_channel: 0
    use_psram: false
    default_transition_length: 2s
    name: "Tree lights"
    effects:
      - pulse:
      - random:
      - strobe: 
      - flicker:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
      - addressable_flicker:
            
binary_sensor:
  - platform: gpio
    name: "Button 1"
    pin:
      number: GPIO14
      inverted: false
      mode:
        input: true
        pulldown: true

  - platform: gpio
    name: "Button 2"
    pin:
      number: GPIO17
      inverted: false
      mode:
        input: true
        pulldown: true

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret iot_wifi_ssid
  password: !secret iot_wifi_password
  power_save_mode: none

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Tree Lights"
    password: ""

  on_connect:
    - if:
        condition:
          wifi.connected:
        then:
          - light.turn_off:
              id: leds
        else:
          - light.turn_on:
              id: leds
              red: 100%
              green: 0 
              blue: 0
              effect: "None"

  on_disconnect:
    - light.turn_on:
        id: leds
        red: 0
        green: 100%
        blue: 100%
        effect: "Scan"


captive_portal:
