esphome:
  name: washing-machine
  platform: ESP8266
  board: esp01_1m

sensor:
  - platform: hlw8012
    sel_pin: 
      number: 12
      inverted: true
    cf_pin: 4
    cf1_pin: 5
    voltage_divider: 1881
    current:
      name: "Washing Machine Current"
    voltage:
      name: "Washing Machine Voltage"
    power:
      name: "Washing Machine Power"
    energy:
      name: "Washing Machine Energy"
    update_interval: 10s

switch:
  - platform: gpio
    id: output_relay
    pin: 14
    name: "Washing Machine Switch"
    restore_mode: ALWAYS_ON
status_led:
  id: output_led
  pin: 
    number: 13
    inverted: true

binary_sensor:
  - platform: gpio
    id: button
    pin: 
      number: 0
    on_click:
      min_length: 50ms
      max_length: 350ms
      then:
        - switch.toggle: output_relay



# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret iot_wifi_ssid
  password: !secret iot_wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Washing-Machine"
    password: ""

captive_portal:
