esphome:
  name: xs-a18-73373e
  platform: ESP8266
  board: esp01_1m

output:
  - platform: esp8266_pwm
    id: output_red
    pin: 0
  - platform: esp8266_pwm
    id: output_green
    pin: 2
  - platform: esp8266_pwm
    id: output_blue
    pin: 5

switch:
  - platform: gpio
    id: output_relay
    pin: 15
    name: "XS-A18 7337e Switch"

binary_sensor:
  - platform: gpio
    id: button
    pin: 
      number: 13
      inverted: true
    on_click:
      min_length: 50ms
      max_length: 350ms
      then:
        - switch.toggle: output_relay

light:
  - platform: rgb
    name: "XS-A18 73373e LED"
    red: output_red
    green: output_green
    blue: output_blue

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "XS-A18-73373E"
    password: ""

captive_portal:
